name: Postman Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/1 * * * *'

jobs:
  postman:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache node_modules
      id: cache-dependencies
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nodejs npm

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman tests
      run: newman run ServeRest.postman_collection.json

    - name: Save cache
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
